/*
 * This source file was generated by the Gradle 'init' task
 */
package io.jwb.aoc

class Aoc {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun printUsage() {
    println("Usage: <program> [year] [day]")
}

fun main(args: Array<String>) {
    if (args.size != 2) {
        printUsage()
        return
    }

    val year = args[0].toIntOrNull()
    val day = args[1].toIntOrNull()

    if (year == null || day == null || year < 2015 || year > 2100 || day < 1 || day > 25) {
        printUsage()
        return
    }

    val className = "io.jwb.aoc.year$year.Day${day.toString().padStart(2, '0')}Kt"
    val clazz =
            try {
                Class.forName(className)
            } catch (e: ClassNotFoundException) {
                println("No implementation found for year $year day $day")
                return
            }

    val method =
            try {
                clazz.getMethod("main", Array<String>::class.java)
            } catch (e: NoSuchMethodException) {
                println("No main method found for year $year day $day")
                return
            }

    method.invoke(null, arrayOf<String>())
}
